#!/bin/bash
#This script is to configure the initial setup for Raspberry Pi for Building Energy project
#Only run this script file once to avoid duplicate configure those variables


#Update new RPI
#apt-get update


#Uncomment these lines to configure wifi network for RPI
#However, if you're using pibakery tools, you don't need these
#echo 'network={' >> /etc/wpa_supplicant/wpa_supplicant.conf
#	echo 'ssid="emblab"' >> /etc/wpa_supplicant/wpa_supplicant.conf
#	echo 'psk=""' >> /etc/wpa_supplicant/wpa_supplicant.conf
#echo ' }' >> /etc/wpa_supplicant/wpa_supplicant.conf


#Configure static IP address for RPI

echo 'interface eth0' >> /etc/dhcpcd.conf
echo 'static ip_address=192.168.0.10/24' >> /etc/dhcpcd.conf
echo 'static routers=192.168.0.1' >> /etc/dhcpcd.conf
echo 'static domain_name_servers=192.168.0.1' >> /etc/dhcpcd.conf

echo '' >> /etc/dhcpcd.conf

echo 'interface wlan0' >> /etc/dhcpcd.conf
echo 'static ip_address=192.168.0.210/24' >> /etc/dhcpcd.conf	
echo 'static routers=192.168.0.1' >> /etc/dhcpcd.conf
echo 'static domain_name_servers=192.168.0.1' >> /etc/dhcpcd.conf


#Adding new user
sudo adduser buildingenergy
sed -i '/Allow members of group sudo to execute any command/i buildingenergy ALL= NOPASSWD: ALL'  /etc/sudoers

#To enable ssh service
systemctl enable ssh

#Reconfigure the connection
#wpa_cli reconfigure

#Creating new SSH keys

if test -d ~/.ssh
then
	echo "this RPI already has SSH directory"

else
	mkdir /home/buildingenergy/.ssh
	chown buildingenergy /home/buildingenergy/.ssh
	sudo -u buildingenergy ssh-keygen -t rsa -C buildingenergy@raspberrypi
	touch /home/buildingenergy/.ssh/authorized_keys 
	chmod 755 /home/buildingenergy/.ssh/authorized_keys
fi

#Adding ssh public key of Jonathan - Minna - Nhut to Raspberry Pi
#Jonathan
echo ' ' >> /home/buildingenergy/.ssh/authorized_keys

#Minna
echo ' ' >> /home/buildingenergy/.ssh/authorized_keys

#Nhut
echo ' ' >> /home/buildingenergy/.ssh/authorized_keys


exit 0


